import "./globals.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Chat AI",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
