import "./globals.css";

import { Metadata } from "next";

import { fontMono, fontSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Next Chat AI",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body
        className="font-sans antialiased,
          fontSans.variable,
          fontMono.variable"
      >
        <main className="bg-light text-black dark:bg-dark dark:text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
